"""order model added

Revision ID: 3e042c0f8a20
Revises: 9c3daba869a4
Create Date: 2020-10-01 23:24:26.060285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e042c0f8a20'
down_revision = '9c3daba869a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_address', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('pickup_Address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'pickup_Address')
    op.drop_column('orders', 'name')
    op.drop_column('orders', 'description')
    op.drop_column('orders', 'delivery_address')
    # ### end Alembic commands ###
